export const names = [
    "Kenanga", "Kamboja", "Cempaka", "Melati Hitam", "Anggrek Dendam", "Bunga Setan", "Bunga Bangkai", "Bunga Puspa", "Bunga Wijaya Kusuma", "Bunga Arjuna", "Harimau Jawa", "Ayam Cemani", "Burung Hantu", "Biawak Hitam", "Ular Sendok", "Kucing Hitam", "Macan Kumbang", "Lutung Kasarung", "Gagak Hitam", "Jenglot", 
    "Roro Jonggrang", "Brawijaya", "Ken Arok", "Kebo Iwa", "Gajah Mada", "Ki Ageng Selo", "Sri Sultan Hamengkubuwono", "Raden Wijaya", "Sunan Kalijaga", "Diponegoro",
    "Keraton", "Candi Prambanan", "Borobudur", "Gunung Lawu", "Parangkusumo", "Pantai Parangtritis", "Sendang Kamal", "Sumur Gumuling", "Lawang Sewu", "Taman Sari",
    "Warung Doyong", "Pohon Beringin", "Pohon Trembesi", "Pohon Keluwih", "Pohon Randu", "Pohon Gayam", "Pohon Asam", "Pohon Pulus", "Pohon Jati", "Pohon Sawo Kecik",
    "Mantra Sirep", "Ajian Jaran Goyang", "Ajian Brajamusti", "Ajian Pengasihan", "Ilmu Pelet", "Ajian Lembu Sekilan", "Ajian Rawarontek", "Ajian Pancasona", "Ajian Semar Mesem", "Ajian Teluh",
    "Semar", "Gareng", "Petruk", "Bagong", "Arjuna", "Bima", "Nakula", "Sadewa", "Srikandi", "Gatotkaca",
    "Keris Kyai Setan Kober", "Keris Sangkelat", "Keris Naga Sasra", "Keris Tumbal", "Keris Kiai Carubuk", "Tombak Kyai Pleret", "Panah Arjuna", "Gada Rujak Polo", "Kujang Sakti", "Tombak Kyai Slamet",
    "Sajen", "Kemenyan", "Keris Pusaka", "Tosan Aji", "Gamelan", "Topeng Panji", "Wayang Kulit", "Wayang Golek", "Wayang Wong", "Jimat Kalimasada",
    "Kendang", "Saron", "Bonang", "Gong", "Rebab", "Suling", "Ketipung", "Kenong", "Gender",
    "Gunung Merapi", "Gunung Merbabu", "Gunung Slamet", "Gunung Kawi", "Gunung Sumbing", "Kraton Surakarta", "Kraton Yogyakarta", "Goa Selarong", "Puncak Gunung Lawu", "Sendang Sono",
    "Pantai Ngobaran", "Pantai Baron", "Pantai Siung", "Pantai Krakal", "Pantai Sundak", "Pantai Timang", "Pantai Pok Tunggal", "Pantai Glagah", "Pantai Depok",
    "Batik", "Kebaya", "Jarik", "Beskap", "Blangkon", "Udeng", "Sarung", "Lurik", "Kain Poleng", "Dodot",
    "Angklung", "Bedug", "Pencak Silat", "Tari Kecak", "Tari Bedhaya", "Tari Gambyong", "Tari Srimpi", "Pringgitan", "Pendopo", "Balairung",
    "Seruni", "Bunga Kantil", "Bunga Mawar Hitam", "Bunga Soka", "Bunga Gandasuli", "Bunga Padma", "Bunga Sedap Malam", "Bunga Tasbih", "Bunga Patma", "Bunga Ciplukan",
    "Harimau Putih", "Anjing Hitam", "Kelelawar", "Ikan Lele", "Burung Kepodang", "Buaya Muara", "Burung Elang Hitam", "Burung Kedasih", "Burung Jalak", "Gajah Sumatera",
    "Putri Hijau", "Nyi Roro Kidul", "Raden Patah", "Jayabaya", "Sultan Agung", "Ki Hajar Dewantara", "Raden Ajeng Kartini", "Ki Ageng Mangir", "Damarwulan", "Mpu Gandring",
    "Puri Mangkunegaran", "Sendang Tirta", "Waduk Gajah Mungkur", "Goa Jatijajar", "Pantai Wediombo", "Gunung Kelud", "Candi Sewu", "Candi Sukuh", "Pantai Karangbolong",
    "Pohon Dewandaru", "Pohon Pule", "Pohon Asem Jawa", "Pohon Waru", "Pohon Cendana", "Pohon Bambu", "Pohon Pinus", "Pohon Kayu Putih", "Pohon Sawo Manila", "Pohon Mangga",
    "Mantra Kecantikan", "Ajian Kalacakra", "Ajian Waringin Sungsang", "Ilmu Kebal", "Ajian Pemikat", "Ajian Tapak Saketi", "Ilmu Santet", "Ajian Wisanggeni", "Ajian Karang", "Ajian Lembu Sekilan",
    "Anoman", "Werkudara", "Antareja", "Karna", "Durga", "Kresna", "Abimanyu", "Samba", "Bagaspati", "Buto Ijo",
    "Keris Empu Gandring", "Keris Kiai Brojomusti", "Keris Kala Rau", "Tombak Kyai Sapu Jagat", "Panah Siwer Geni", "Tombak Kyai Baru Klinting", "Keris Nogososro", "Keris Sabuk Inten", "Keris Sengkelat", "Panah Pasopati",
    "Sesajen", "Dupa", "Menyan Arab", "Keris Brojol", "Tosan Kujang", "Wayang Krucil", "Wayang Thengul", "Wayang Klitik", "Wayang Wahyu", "Jimat Cundrik",
    "Angklung Reyog", "Bende", "Gendang", "Kenong Teluk", "Kenong Gandul", "Kethuk", "Slenthem", "Slendro", "Gambang", "Siter",
    "Gunung Dieng", "Gunung Sindoro", "Gunung Telomoyo", "Gunung Ungaran", "Kraton Mangkunegaran", "Kraton Pakualaman", "Goa Kiskendo", "Gunung Muria", "Sendang Drajat",
    "Pantai Nguyahan", "Pantai Sepanjang", "Pantai Sadranan", "Pantai Drini", "Pantai Samas", "Pantai Kukup", "Pantai Seruni", "Pantai Gesing", "Pantai Watu Lawang", "Pantai Mbirit",
    "Songket", "Kain Jumputan", "Kain Kebat", "Kain Endek", "Kain Batik Tulis", "Kain Ulos", "Kain Poleng Bali", "Kain Sasirangan", "Kain Rangrang", "Kain Prada",
    "Angklung Kanekes", "Angklung Caruk", "Calung", "Gong Kemodong", "Gong Beri", "Gendang Bali", "Kecapi", "Sasando", "Suling Gamelan", "Tari Barong",
  ];
